### PR TITLE
Update dockerfile

### PR DESCRIPTION
**Pull request by waeljammal**

### CODE REVIEW

**Comment by waeljammal** [comment]
# go-cover-view

**Comment by waeljammal** [comment]
# go-cover-view

**Comment by waeljammal** [comment]
# go-cover-view

**Comment by waeljammal** [comment]
# go-cover-view

**Comment by waeljammal** [comment]
# go-cover-view

**Comment by waeljammal** [comment]
# go-cover-view

**Review by azarc-jono-langley — APPROVED** [review]

**Pull request merged**
