### PR TITLE
Added ubuntu jammy base docker image for modules

### PR DESCRIPTION
**Pull request by waeljammal**

### CODE REVIEW

**Comment by waeljammal** [comment]
# go-cover-view

**Review by toka03 — APPROVED** [review]

**Comment by waeljammal** [comment]
# go-cover-view

**Comment by waeljammal** [comment]
# go-cover-view

**Comment by waeljammal** [comment]
# go-cover-view

**Comment by azarc-jono-langley** [comment]
I think we should rather provide binaries which can be included in the module builds rather than having loads of different flavour base images.

**Pull request closed without merging**
